version: 2.1

orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@1.7.0

jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/frontend:latesv1 .

  push:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/frontend:latesv1:${CIRCLE_SHA1}

workflows:
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
