version: 2.1

# Define Orbs
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@1.7.0

jobs:
  build:
    executor:
      name: node/default
      tag: '14'  # Specify the Node.js version
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/frontend:latesv1:${CIRCLE_SHA1} .

  push:
    executor: docker/docker
    steps:
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo $DOCKERHUB_ACCESS_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/frontend:latesv1:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
