version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build Docker image
          command: docker build -t imranahmedn/frontend-test-1:${CIRCLE_SHA1} .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push imranahmedn/frontent-test-1:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
