version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
      - run:
          name: Run tests
          command: npm test
  build-and-push:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t frontendv1 -t imranahmedn/frontendv2:latest .
      - run:
          docker login -u $DOCKERHUB_USERNAME -p $CIRCLECI_DOCKERHUB_PASSWORD
      - run:
          name: Push Docker image to Docker Hub
          command: docker push imranahmedn/frontendv2:latest
workflows:
  version: 2
  build:
    jobs:
      - test
      - build-and-push:
          requires:
            - test